<?php

namespace Phpackage\Autodns\Model;

interface DomainActionConstants
{
    const CREATE = 'CREATE';
    const UPDATE = 'UPDATE';
    const UPDATE_OWNER_CHANGE = 'UPDATE_OWNER_CHANGE';
    const UPDATE_DNSSEC = 'UPDATE_DNSSEC';
    const UPDATE_NAMESERVER = 'UPDATE_NAMESERVER';
    const DELETE = 'DELETE';
    const TRANSIT = 'TRANSIT';
    const TRANSFER = 'TRANSFER';
    const TRANSFER_INTERN = 'TRANSFER_INTERN';
    const TRANSFER_INTERN_REGISTRAR_CHANGE = 'TRANSFER_INTERN_REGISTRAR_CHANGE';
    const TRANSFER_INTERN_REGISTRAR_CHANGE_RUNTIME_TAKEOVER = 'TRANSFER_INTERN_REGISTRAR_CHANGE_RUNTIME_TAKEOVER';
    const IMPORT = 'IMPORT';
    const MIGRATE = 'MIGRATE';
    const RESTORE = 'RESTORE';
    const RESTORE_NE = 'RESTORE_NE';
    const RESTORE_RENEW = 'RESTORE_RENEW';
    const RESTORE_ARGP = 'RESTORE_ARGP';
    const RENEW = 'RENEW';
    const AUTHINFO = 'AUTHINFO';
    const AUTHINFO_2 = 'AUTHINFO_2';
    const UPDATE_STATUS = 'UPDATE_STATUS';
    const REGISTRAR_UPDATE_STATUS = 'REGISTRAR_UPDATE_STATUS';
    const UPDATE_COMMENT = 'UPDATE_COMMENT';
    const AUTOUPDATE_DNS = 'AUTOUPDATE_DNS';
    const OWNERCHANGE = 'OWNERCHANGE';
    const OWNERCHANGE_TRANSFER = 'OWNERCHANGE_TRANSFER';
    const OWNERCHANGE_TRANSFER_INTERN = 'OWNERCHANGE_TRANSFER_INTERN';
    const OWNERCHANGE_TRANSFER_INTERN_REGISTRAR_CHANGE = 'OWNERCHANGE_TRANSFER_INTERN_REGISTRAR_CHANGE';
    const PREACK = 'PREACK';
    const WHOIS_REGISTRY_STATUS = 'WHOIS_REGISTRY_STATUS';
    const DOMAIN_AWAY = 'DOMAIN_AWAY';
    const TRANSFER_OUT_AUTOACK = 'TRANSFER_OUT_AUTOACK';
    const DROP = 'DROP';
    const AUTHINFO_CREATE = 'AUTHINFO_CREATE';
    const AUTHINFO_DELETE = 'AUTHINFO_DELETE';
    const AUTOUPDATE_DEFERRED = 'AUTOUPDATE_DEFERRED';
    const DOMAIN_BUY = 'DOMAIN_BUY';
}
